# It just finds services with the "release: prometheus" label.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-microservice-monitor
  namespace: monitoring # We create this in the 'monitoring' namespace
  labels:
    release: prometheus # This label is critical!
spec:
  namespaceSelector:
    matchNames:
      - default # We're looking for services in the 'default' namespace
  selector:
    matchLabels:
      release: prometheus # It will find any Service with this label
  endpoints:
  - port: http-metrics # It will scrape the port named 'http-metrics'
    interval: 15s
