apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Inby-420/auto-stack.git'
      targetRevision: HEAD
      path: k8s-manifests
    - repoURL: 'https://github.com/Inby-420/auto-stack.git'
      targetRevision: HEAD
      path: consul-config
      ref: values  
    - repoURL: https://helm.releases.hashicorp.com
      chart: consul
      targetRevision: "1.4.3"
      helm:
        valueFiles:
          - $values/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: consul
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
