apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # --- THIS IS THE SIMPLIFIED SOURCE ---
  # We are only using ONE source now: the Helm chart
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: consul
    targetRevision: "1.4.3" # Pin to a specific, stable version
    
    helm:
      values: |
        global:
          name: consul
          enterpriseLicense:
            secretName: ""
          # Completely disable Gateway API (which fixes the CRD errors)
          enableConsulGatewayAPI: false

        # Disable all gateway-related components
        connectInject:
          enabled: true
          default: false
        controller:
          enabled: false
        gateway:
          enabled: false
        apiGateway:
          enabled: false
        meshGateway:
          enabled: false
        ingressGateways:
          enabled: false
        terminatingGateways:
          enabled: false

        # Run a lightweight, single-node server
        server:
          replicas: 1

        ui:
          enabled: true
          service:
            type: ClusterIP

        # This will now be processed correctly
        kv:
          enabled: true
          defaultConfig:
            - key: "config/tps"
              value: "1.0"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: consul # Deploy into its own namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
