apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.28.0" # A recent, stable version
    helm:
      values: |
        global:
          # Run in lightweight "dev" mode
          # This disables all production complexity
          dev: true
        
        # It's the agent that will inject secrets into our app pods
        injector:
          enabled: true
          
          # Tell the injector to work with K3s's CNI
          agent:
            cni:
              enabled: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault # Deploy into its own 'vault' namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
