# This file defines your CI (Continuous Integration) pipeline
# It runs on GitHub's servers to build and push your Docker images.

name: Build and Push Docker Images

on:
  # This tells GitHub to run the workflow on any push...
  push:
    branches:
      - main # ...to the main branch

env:
  # Your GitHub Container Registry (GHCR) URL
  REGISTRY: ghcr.io
  # The "owner" is your GitHub username. We force it to lowercase.
  IMAGE_OWNER: inby-420
  # The "image name" will be your repo name
  IMAGE_NAME: auto-stack

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # This gives the job permission to write to GHCR

    strategy:
      matrix:
        # We define a "matrix" to build all 3 apps in parallel
        # The "image" is the sub-name, the "dockerfile" is the path
        service:
          - image: worker-node
            dockerfile: ./worker-node/Dockerfile
            context: ./worker-node
          - image: result-node
            dockerfile: ./result-node/Dockerfile
            context: ./result-node
          - image: traffic-sender
            dockerfile: ./traffic-sender/Dockerfile
            context: ./traffic-sender

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # This is your GitHub username
          password: ${{ secrets.GITHUB_TOKEN }} # This is a temporary token, automatically created

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          # This is the fix. We are now pushing TWO tags:
          # 1. A unique tag based on the Git SHA (e.g., ...:81ce24cc2d)
          # 2. The simple "latest" tag
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}/${{ matrix.service.image }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}/${{ matrix.service.image }}:latest
